test12_bbs/urls.py
from django.contrib import admin
from django.urls import path,re_path
from app01 import views
from test12_bbs import settings
from django.views.static import serve

urlpatterns = [

   path('admin/', admin.site.urls),
    path('bootstrap',views.bootstrapcs),
    re_path(r'^register/',views.register,name='reg'),
    re_path(r'^login/',views.login,name='login'),
    #图片验证码相关操作
    re_path(r'^get_code',views.get_code,name="get"),
    #首页
    re_path(r'^$',views.home,name='home'),
    #修改密码
    re_path(r'^set_password/',views.set_password,name="set_pas"),
    #退出登录
    re_path(r'^/logout/',views.logout,name='logout'),
    #暴露后端指定文件夹资源
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    #点赞点踩
    re_path(r'^up_or_down/',views.up_or_down),
    #文章评论
    re_path(r"^comment/",views.comment),
    #后台管理
    re_path(r'^backend/',views.backend),
    #添加文章
    re_path(r'^add/article/',views.add_article),
    re_path(r'^update/article/(?P<edit_id>\d+)/',views.update_article,name="article_update"),  #修改文章
    #编辑器上传图片接口
    re_path(r'^upload_image/',views.upload_image),
    re_path(r'^set/avatar/',views.set_avatar),  #修改头像

    #个人站点页面
    re_path(r'^(?P<username>\w+)/$',views.site,name='site'),
    #侧边栏筛选功能
    # re_path(r'^(?P<username>\w+)/category/(\d+)/',views.site),
    # re_path(r'^(?P<username>\w+)/tag/(\d+)/',views.site),
    # re_path(r'^(?P<username>\w+)/archive/(\d+)/', views.site),
    #以上三条url合并成一条
    re_path(r'^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)/',views.site),

    #文章详情页
    re_path(r'^(?P<username>\w+)/article/(?P<article_id>\d+)/',views.article_detail),

    #删除文章
    re_path(r'^article_delete/(\d+)/',views.article_delete,name='article_delete'),
    # #编辑文章
    # re_path(r'article_edit/(\d+)/',views.article_edit,name='article_edit'),


]

app01/models.py
from django.db import models

# Create your models here.
"""
先写普通字段，再写外键字段
"""
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    phone = models.IntegerField(verbose_name="手机号",null=True,blank=True)
    #null=true表示数据库字段可以为空，blank=True，admin后台字段可以为空
    avatar = models.FileField(upload_to='avatar/',default='avatar/default.png')#头像
    """
    给avatar字段传文件对象，该文件会自动存储到avatar文件下，然后avatar字段只保存文件路径avatar/dafault.png
    """
    create_time = models.DateField(auto_now_add=True)

    blog = models.OneToOneField(to='Blog',null=True,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural ="用户信息"

    def __str__(self):
        return self.username


class Blog(models.Model):
    site_name = models.CharField(verbose_name="站点名称",max_length=32)
    site_title = models.CharField(verbose_name="站点标题",max_length=32)
    site_theme = models.CharField(verbose_name="站点样式",max_length=64)  #存CSS/JS的文件路径，模拟多背景样式操作

    class Meta:
        verbose_name_plural ="个人站点"

    def __str__(self):
        return self.site_name


class Category(models.Model):
    name = models.CharField(verbose_name="文章分类",max_length=32)
    blog = models.ForeignKey(to='Blog',null=True,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural ="分类"

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(verbose_name="标签",max_length=32)
    blog = models.ForeignKey(verbose_name="站点名称",to='Blog',null=True,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural ="标签"

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(verbose_name="文章标题",max_length=255)
    desc = models.CharField(verbose_name="文章简介",max_length=255)
    #文章内容有很多，一般使用TextField
    content = models.TextField(verbose_name="文章内容")
    create_time = models.DateField(auto_now_add=True)
    # 数据库字段设计优化
    up_num = models.IntegerField(verbose_name="点赞数", default=0)
    down_num = models.IntegerField(verbose_name="点踩数", default=0)
    comment_num = models.BigIntegerField(verbose_name="评论数", default=0)
    #外键字段
    blog = models.ForeignKey(to='Blog',null=True,on_delete=models.CASCADE,verbose_name="个人站点")
    category = models.ForeignKey(to='Category',null=True,on_delete=models.CASCADE,verbose_name="分类")
    tags = models.ManyToManyField(to='Tag',
                                  through='Article_Tag',
                                  through_fields=('article','tag')
                                  )

    class Meta:
        verbose_name_plural ="文章"

    def __str__(self):
        return self.title

class Article_Tag(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag,on_delete=models.CASCADE)


    class Meta:
        verbose_name_plural ="文章标签"


class UpAndDown(models.Model):
    user = models.ForeignKey(to="UserInfo",on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article",on_delete=models.CASCADE)
    is_up = models.BooleanField()  #传布尔值

    class Meta:
        verbose_name_plural ="调整顺序"


class Comment(models.Model):
    user = models.ForeignKey(to='UserInfo',on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article",on_delete=models.CASCADE)
    content = models.CharField(verbose_name="评论内容",max_length=255)
    comment_time = models.DateTimeField(verbose_name="评论时间",auto_now_add=True)
    #自关联
    parent = models.ForeignKey(to='self',null=True,on_delete=models.CASCADE)  #Null=True，因为有些piglet是根评论

    class Meta:
        verbose_name_plural ="评论"

    def __str__(self):
        return self.user

app01/forms.py
# 针对用户表的forms组件代码
from django import forms
from app01 import models


class MyRegForm(forms.Form):
    username = forms.CharField(label='用户名', min_length=3, max_length=8,
                               error_messages={
                                   'required': '用户名不能为空',
                                   'min_length': '用户名最少3位',
                                   'max_length': '用户名最多8位',
                               },
                               # 还需要让标签有bootstrap样式
                               widget=forms.widgets.TextInput(attrs={'class': 'form-control'})
                               )
    password = forms.CharField(label='密码', min_length=3, max_length=8,
                               error_messages={
                                   'required': '密码不能为空',
                                   'min_length': '密码最少3位',
                                   'max_length': '密码最多8位',
                               },
                               # 还需要让标签有bootstrap样式
                               widget=forms.widgets.PasswordInput(attrs={'class': 'form-control'})
                               )
    confirm_password = forms.CharField(label='确认密码', min_length=3, max_length=8,
                                       error_messages={
                                           'required': '密码不能为空',
                                           'min_length': '密码最少3位',
                                           'max_length': '密码最多8位',
                                       },
                                       # 还需要让标签有bootstrap样式
                                       widget=forms.widgets.PasswordInput(attrs={'class': 'form-control'})
                                       )
    email = forms.EmailField(label="邮箱",
                             error_messages={
                                 'required': '邮箱不能为空',
                                 'invalid': '邮箱格式不正确'
                             },
                             widget=forms.widgets.EmailInput(attrs={'class': 'form-control'})
                             )

    # 钩子函数。局部钩子：校验用户名是否已存在
    def clean_username(self):
        username = self.cleaned_data.get('username')
        # 去数据库中校验
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 提示信息
            self.add_error('username', '用户名已存在')
        return username

    # 全局钩子：校验两次是否一致
    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if not password == confirm_password:
            self.add_error('confirm_password', '两次输入不一致')
        return self.cleaned_data

templates/backend/add_article.html
{% extends 'backend/backend_base.html' %}
{% block article %}
     <h3>添加文章</h3>
    {# 直接利用form表单提交数据 #}
    <form action="" method="post">
    {% csrf_token %}
    <p>标题</p>
    <div>
        <input type="text" name="title" class="form-control">
    </div>
    <p>内容</p>
    <div>
        <textarea name="content" id="id_content" cols="60" rows="10"></textarea>
    </div>
    <p>分类</p>
    <div>
        {% for category in category_list %}
            <input type="radio" value="{{ category.pk }}" name="category">{{ category.name }}
        {% endfor %}
    </div>
    <p>标签</p>
    <div>
        {% for tag in tag_list %}
            <input type="checkbox" value="{{ tag.pk }}" name="tag">{{ tag.name }}
        {% endfor %}
    </div>
    <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}
{% block js %}
    {% load static %}
<script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#id_content',{
                    width:'100%',
                    height:'400px',
                    resizeType: 1,
                    uploadJson : '/upload_image/',  //上传图片的后端提交路径
                      extraFileUploadParams : {
                       'csrfmiddlewaretoken':'{{ csrf_token }}'
                }
                })
        });
</script>
{% endblock %}

templates/backend/backend.html
{% extends 'backend/backend_base.html' %}

{% block article %}
        {# 接收当前用户所有文章 #}
    <table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>标题</th>
        <th>评论数</th>
        <th>点赞数</th>
        <th>修改</th>
        <th>谨慎删除</th>

    </tr>
    </thead>
    <tbody>
    {% for article in page_queryset %}
    <tr>
        <td><a href="/{{ request.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></td>
        <td>{{ article.comment_num }}</td>
        <td>{{ article.up_num }}</td>
        <td><a href="/update/article/{{ article.pk }}/" edit_id="{{ article.pk }}">修改</a></td>
        <td><a href="{% url 'article_delete' article.pk %}" delete_id="{{ article.pk }}">删除不可恢复</a></td>
{#        <a href={% url "article_delete' article_obj.pk %}" class="btn-danger btn-sm">删除</a>#}
    </tr>
    {% endfor %}
    </tbody>
    </table>
    <div class="pull-right">
    {{ page_obj.page_html|safe }}
    </div>
{% endblock %}

templates/backend/backend_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台管理</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% block js %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">{{ request.user.blog.site_title }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">博客 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">文章</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">更多 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://www.baidu.com/">找一下百度</a></li>
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">更多操作 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">修改密码</a></li>
                            <li><a href="/set/avatar/">修改图像</a></li>
                            <li><a href="/backend/">后台管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'logout' %}">注销</a></li>
                        </ul>
                        <!-- Large modal -->
                        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
                             aria-labelledby="myLargeModalLabel">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <h2 class="text-center">修改密码</h2>
                                    <div class="row">
                                        <div class="col-md-8 col-md-offset-2">
                                            <div class="form-group">
                                                <label for="">用户名</label>
                                                <input type="text" disabled value="{{ request.user.username }}"
                                                       class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">原密码</label>
                                                <input type="password" id="id_old_password" name="old_password"
                                                       class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">新密码</label>
                                                <input type="password" id="id_new_password" name="new_password"
                                                       class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">确认密码</label>
                                                <input type="password" id="id_confirm_password" class="form-control">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">取消
                                                </button>
                                                <button class="btn btn-primary" id="id_edit">修改</button>
                                                <span style="color: red" id="password_error"></span>
                                            </div>
                                            <br>
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </li>
                {% else %}
                    <li><a href="{% url 'reg' %}">注册</a></li>
                    <li><a href="{% url  'login' %}">登录</a></li>
                {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="row">
    <div class="col-md-2">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        更多操作
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <a href="/add/article/">添加文章</a>

                    </div>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <a href="">添加随笔(暂未开放）</a>
                    </div>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <a href="">草稿箱</a>
                    </div>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <a href="">其他</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-10">
            <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                          data-toggle="tab">文章</a></li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                           data-toggle="tab">随笔</a></li>
                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">草稿</a>
                </li>
                <li role="presentation"><a href="#file" aria-controls="file" role="tab" data-toggle="tab">文件</a>
                </li>
                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">设置</a>
                </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    {% block article %}

                        {% endblock %}
                </div>
                <div role="tabpanel" class="tab-pane" id="profile">
                    {% block essay %}
                        {% endblock %}
                </div>
                <div role="tabpanel" class="tab-pane" id="messages">草稿页面</div>
                <div role="tabpanel" class="tab-pane" id="file">文件页面</div>
                <div role="tabpanel" class="tab-pane" id="settings">设置页面</div>
            </div>
        </div>

        </div>
    </div>

</body>
</html>

templates/backend/update_article.html
{% extends 'backend/backend_base.html' %}
{% block article %}
     <h3>修改文章</h3>
    {# 直接利用form表单提交数据 #}
    <form action="" method="post">
    {% csrf_token %}
    <p>标题</p>
    <div>
        <textarea name="title" cols="160">{{ article.title }}</textarea>
    </div>
    <p>内容</p>
    <div>
        <textarea name="content" id="id_content" cols="60" rows="10">{{ article.content }}</textarea>
    </div>
{#    <p>分类</p>#}
{#    <div>#}
{#        {% for category in category_list %}#}
{#            <input type="radio" value="{{ category.pk }}" name="category">{{ category.name }}#}
{#        {% endfor %}#}
{#    </div>#}
{#    <p>标签</p>#}
{#    <div>#}
{#        {% for tag in tag_list %}#}
{#            <input type="checkbox" value="{{ tag.pk }}" name="tag">{{ tag.name }}#}
{#        {% endfor %}#}
{#    </div>#}
    <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}
{% block js %}
    {% load static %}
<script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#id_content',{
                    width:'100%',
                    height:'400px',
                    resizeType: 1,
                    uploadJson : '/upload_image/',  //上传图片的后端提交路径
                      extraFileUploadParams : {
                       'csrfmiddlewaretoken':'{{ csrf_token }}'
                }
                })
        });
</script>
{% endblock %}